# To send requests inline - install `humao.rest-client` from App Store in VSC

# Health Api
GET http://localhost:3000/health HTTP/1.1

###

# POST a user
POST http://localhost:3000/api/user HTTP/1.1
Content-Type: application/json

{
    "given_name": "Jonh",
    "family_name": "Doe",
    "name": "Jonh Doe",
    "email": "doe.jonh@gmail.com"
}

###

# GET all users
GET http://localhost:3000/api/user HTTP/1.1

###