import mongoose from "mongoose";

const userSchema = new mongoose.Schema({
    given_name: { type: String, required: true },
    family_name: { type: String, required: true },
    name: { type: String, required: true },
    email: { type: String, required: true },
    phone: { type: String, maxlength: 10 },
    date_created: { type: Date, default: Date.now },
    date_modified: { type: Date, default: Date.now },
    is_deleted: { type: Boolean, default: false },

    /**patient_id: { type: String, required: true },
    birth_date: { type: Date, required: true },
    gender: { type: String, enum: ["Male", "Female"], required: true },
    test_date: {type: Date, required: true},
    pincode: {type: Number, required: true},
    state: {type: Number, required: true},
    leukocyte_count_WBC: {required: true},
    erythrocyte_count_RBC: {required: true},
    hemoglobin: {required: true},
    hematocrit: {required: true},
    mean_corpuscular_volume_MCV: {required: true},
    mean_corpuscular_hemoglobin_MCH: {required: true},
    mean_corpuscular_hemoglobin_concentration_MCHC: {required: true},
    erythrocyte_distribution_width_RDW: {required: true},
    platelet_count: {required: true},
    mean_platelet_volume_MPV: {required: true},
    neutrophils_count: {required: true},
    lymphocyte_count: {required: true},
    monocyte_count: {required: true},
    eosinophils_count: {required: true},
    basophils_count: {required: true},
    neutrophils_percent:  {required: true},
    lymphocyte_percent:  {required: true},
    monocyte_percent:  {required: true},
    eosinophils_percent:  {required: true},
    basophils_percent:  {required: true},
    glucose: {required: true},
    urea: {required: true},
    potassium_in_serum: {required: true},
    sodium_in_serum: {required: true},
    bilirubin_total: {required: true},
    bilirubin_direct: {required: true},
    creatinine: {required: true},
    alkaline_phosphatase: {required: true},
    aspartate_aminotransferase_AST_GOT: {required: true},
    alanine_aminotransferase_ALT_GPT: {required: true},
    igg_serum: {required: true},
    igm_serum: {required: true},
    date_created: { type: Date, default: Date.now },
    date_modified: { type: Date, default: Date.now },
    is_deleted: { type: Boolean, default: false },
    **/
});

const user = mongoose.model("User", userSchema);

export default user;
